#!/bin/bash

# VirtualBox Power Driver for MAAS (Metal as a Service)
# Copyright 2021 Saeid Bostandoust <ssbostan@linuxmail.org>

echo "INFO: Welcome to VirtualBox Power Driver for MAAS (vboxpower)"

# for logging
LOG_FILE="/var/log/vboxpower-deploy.log"
exec &> >(tee -a "$LOG_FILE")

which python3 &> /dev/null

if [ $? -ne 0 ]; then
    echo "ERROR: Python3 is not installed."
    exit 1
fi

which pip3 &> /dev/null

if [ $? -ne 0 ]; then
    echo "ERROR: Pip3 is not installed."
    exit 1
fi

which virtualbox &> /dev/null

if [ $? -ne 0 ]; then
    echo "ERROR: VirtualBox is not installed."
    exit 1
else
    echo "INFO: VirtualBox is installed on the system."
fi

pip3 freeze | grep vboxapi &> /dev/null

if [ $? -ne 0 ]; then
    echo "ERROR: VirtualBox SDK is not installed."
    exit 1
else
    echo "INFO: VirtualBox SDK is installed on the system."
fi

pip3 install -r requirements.txt &> /dev/null

if [ $? -ne 0 ]; then
    echo "ERROR: Cannot install the required packages."
    exit 1
else
    echo "INFO: Required packages are installed successfully."
fi

cp vboxpower.service /etc/systemd/system/vboxpower.service

mkdir -p /opt/maas/vboxpower
cp vboxpower.py /opt/maas/vboxpower/vboxpower.py

echo "INFO: Starting vboxpower service."

systemctl daemon-reload
systemctl enable --now vboxpower.service

if [ systemctl is-active --quiet vboxpower.service ]; then
    echo "INFO: vboxpower service is running."
else
    echo "vboxpower failed to start and it is not running . Check log at $LOG_FILE"
    exit 1
fi
echo "deployment completed. Consider checking log at $LOG_FILE"


